version: '3.8'

services:
  nginx:
   # image: local-nginx
    build: ./nginx/
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  python-app:
   # image: local-python-app
    build: ./Python/
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
    
